# Use the official Node.js image
FROM node:20.15.0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the src and public directories
COPY src ./src
COPY public ./public

# Build the app
RUN npm run build

# Install serve globally
RUN npm install -g serve

# Copy the entry point script
COPY entrypoint.sh /app/entrypoint.sh

# Make the entry point script executable
RUN chmod +x /app/entrypoint.sh

# Expose port 3000
EXPOSE 3000

# Use the entry point script and start the app using serve
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["serve", "-s", "build", "-l", "3000"]
